import test from 'node:test';
import assert from 'node:assert/strict';
import { dashboardHtml, publicTelemetry, createDashboardServer } from '../runtime/dashboard.mjs';
import { createBoundedSwarmLab, assertSwarmLabSafe } from '../runtime/boundary/swarm-lab.mjs';

test('operations dashboard exposes telemetry but stays read-only',()=>{const page=dashboardHtml();assert.match(page,/Ruflo-inspired Swarm Lab/);assert.match(page,/Authority Guardrails/);assert.match(page,/api\/telemetry/);assert.doesNotMatch(page,/<button\b/i);assert.doesNotMatch(page,/<form\b/i);assert.doesNotMatch(page,/innerHTML/);const t=publicTelemetry();assert.equal(t.swarm.authority,'NONE')});
test('telemetry endpoint is GET-only',async()=>{const server=createDashboardServer({port:0});await new Promise(r=>server.once('listening',r));try{const p=server.address().port;const out=await fetch(`http://127.0.0.1:${p}/api/telemetry`);assert.equal(out.status,200);const body=await out.json();assert.equal(body.swarm.mode,'LAB_ONLY');const post=await fetch(`http://127.0.0.1:${p}/api/telemetry`,{method:'POST'});assert.equal(post.status,405)}finally{server.closeAllConnections?.();await new Promise(r=>server.close(r))}});
test('bounded swarm lab permits only parent-authority subsets',()=>{const s=createBoundedSwarmLab({task_id:'demo',parent_allow:['src/**'],agents:[{id:'builder',role:'builder',workspace_mode:'DISPOSABLE_WRITE',allow:['src/**']},{id:'reviewer',role:'reviewer',workspace_mode:'READ_ONLY'}]});assert.equal(assertSwarmLabSafe(s),true);assert.equal(s.coordinator_may_execute,false);assert.equal(s.swarm_consensus_may_approve,false)});
test('swarm lab fails closed on authority expansion, write claims and budget overflow',()=>{assert.throws(()=>createBoundedSwarmLab({task_id:'x',parent_allow:['src/**'],agents:[{id:'a',role:'x',workspace_mode:'DISPOSABLE_WRITE',allow:['.github/**']}]}),/AUTHORITY_EXPANSION/);assert.throws(()=>createBoundedSwarmLab({task_id:'x',parent_allow:['src/**'],agents:[{id:'a',role:'x',workspace_mode:'READ_ONLY',allow:['src/**']}]}),/READ_ONLY_ALLOW_FORBIDDEN/);assert.throws(()=>createBoundedSwarmLab({task_id:'x',max_agents:1,max_parallel:1,agents:[{id:'a',role:'x'},{id:'b',role:'x'}]}),/AGENT_BUDGET_EXCEEDED/)});
