import fs from 'node:fs';
import path from 'node:path';
const input = JSON.parse(fs.readFileSync(0, 'utf8'));
if (Object.keys(process.env).some(key => key.startsWith('BOUNDED_AGENT_'))) throw new Error('WORKER_ENV_LEAK');
const { task, workspace } = input;
if (!task?.task_id || !workspace) throw new Error('BUILDER_INPUT_INVALID');
const out = path.join(workspace, 'demo-output');
fs.mkdirSync(out, { recursive: true });
fs.writeFileSync(path.join(out, 'artifact.txt'), `${task.task_id}\nsynthetic reversible demo change\n`);
process.stdout.write(JSON.stringify({ status: 'PASS', artifact: 'demo-output/artifact.txt' }));
